image: agoradigital/frontend-cicd:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # CONTAINER_TEST_IMAGE: $CI_PROJECT_NAME:dev
  # CONTAINER_RELEASE_IMAGE: $CI_PROJECT_NAME
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:gitlab-ci-dev
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:gitlab-ci

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - export API_IMAGE_TAG=$CONTAINER_TEST_IMAGE

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml -f deploy/prod.yml build
    - docker push $CONTAINER_TEST_IMAGE

tests:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker-compose -f docker-compose.yml -f deploy/prod.yml run api sh -c './manage.py test_all'
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - curl --fail -XPOST "$DEPLOY_WEBHOOK"
  only:
    - master
