image: agoradigital/frontend-cicd:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  COMPOSE_CMD: docker-compose -f docker-compose.yml -f deploy/prod.yml

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - $COMPOSE_CMD pull || true
    - $COMPOSE_CMD build
    - $COMPOSE_CMD push

tests:
  stage: test
  script:
    - $COMPOSE_CMD pull
    - $COMPOSE_CMD run api sh -c './manage.py test_all'
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
