# Compose used for development
# This file is needed because volumes are appended on override.
# So prod would also have dev's volumes, that shouldn't happen.

version: '3.5'

services:

  api:
    build:
      context: ${BACKEND_PATH:-.}
    image: agoradigital/agorapi-dev
    container_name: agorapi
    tty: true
    environment:
      - DEBUG=True
    volumes:
      - ${BACKEND_PATH:-.}:/agora-digital-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
