# Compose used as base for dev and prod

version: '3.2'

services:    

  db:
    image: postgres:10.5-alpine
    container_name: dbapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
