# Compose used for production

version: '3'

services:

  httpapi:
    image: nginx:1.15-alpine
    container_name: httpapi
    restart: always
    volumes:
      - app_static:/app_static
      - app_sockets:/sockets
      - app_deploy_config:/etc/nginx/conf.d:ro
    ports:
      - "9002:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: agoradigital/agorapi
    container_name: agorapi
    env_file:
      - .env.development
      - deploy/env
    volumes:
      - app_sockets:/sockets
      - app_static:/agora-digital-backend/static
      - app_deploy_config:/agora-digital-backend/deploy/nginx:ro
    depends_on:
      - db

  # web:
  #   image: agoradigital/web:1.0
  #   container_name: agoraweb
  #   ports:
  #     - "9001:80"

volumes:
  postgres_data:
  app_sockets:
  app_static:
  app_deploy_config:
